# Application Information
spring.application.name=aviation-api
info.app.name=${spring.application.name}
info.app.description=Aviation API Service: provides information about airports.
info.app.version=project.version@
# Web server configuration
server.port=8092

# Airport client configuration
airport.client.enabled=true
airport.client.retry.delay=200
airport.client.retry.maxDelay=2000
airport.client.retry.maxAttempts=5
airport.client.cache.evictIntervalMs=15000

spring.cloud.openfeign.client.config.airport-client.url=https://api.aviationapi.com/v1/
spring.cloud.openfeign.client.config.airport-client.connectTimeout=5000
spring.cloud.openfeign.client.config.airport-client.readTimeout=5000
spring.cloud.openfeign.client.config.airport-client.loggerLevel=full
spring.cloud.openfeign.client.config.airport-client.micrometer.enabled=true
logging.level.com.xevgnov.aviation.client.AviationAirportClient=DEBUG
feign.client.config.default.loggerLevel=full

# Management and Observability configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=read_only
management.endpoint.info.show-details=always
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# OTLP Exporter configuration
#management.otlp.tracing.endpoint=${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
#management.otlp.metrics.export.url=${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
otel.exporter.otlp.endpoint=${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
otel.exporter.otlp.protocol=http/protobuf
otel.logs.exporter=none
otel.metrics.exporter=none
logging.config=classpath:logback.xml